ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Models/AssetTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.AssetTracking.Models
{
    public class AssetTypeViewModel
    {
        //public int? Id { get; set; }
        //Name
        [Display(Name = "Enter the type of asset")]
        [Required]
        public string Name { get; set; }
    }
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Models/AssetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.AssetTracking.Models
{
    public class AssetViewModel
    {
        [Required]
        public int? Id { get; set; }
        public string Model { get; set; } //Not required
        [Required]
        public string Manufacturer { get; set; }
        [Display(Name = "Asset Type")]
        public int? AssetTypeId { get; set; }

        [Required]
        [Display(Name = "Tag Number")]
        public string TagNumber { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }
        [Display(Name = "Asset Type")]
        public string AssetType { get; set; }
    }
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Models/ErrorViewModel.cs
using System;

namespace Presentation.AssetTracking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.AssetTracking;
using Microsoft.AspNetCore.Mvc;
using Presentation.AssetTracking.Models;
using Domain.AssetTracking;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Collections;

namespace Presentation.AssetTracking.Controllers
{
    public class AssetController : Controller
    {
        //listing all current assets
        public IActionResult Index()
        {
            //Check ViewComponents/AssetsByType for list codes
            ViewBag.AssetTypes = GetAssetTypes(); //Connection to dropdown menu (for filtering)
            return View();
        }


        //Creating new asset
        public IActionResult Create()
        {
            var aType = AssetTypeManager.GetAsKeyValuePairs();
            var list = new SelectList(aType, "Value", "Text");
            ViewBag.AssetTypeId = list; //Different then GetAssetTypes (I did not want it to show "All" on index 0 while adding new assets)
            return View();
        }


        //Saving the new asset
        [HttpPost]
        public IActionResult Create(Asset asset)
        {
            try
            {
                AssetManager.Add(asset);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        //******Filtering by asset type******///

        //**Optional** total of selected asset along with the list, (didn't work)
        //public IActionResult Total(int id)
        //{
        //    var filteredAssets = AssetManager.GetAllByAssetType(id);
        //    var result = $"Total Assets: {filteredAssets.Count}";
        //    return Content(result);
        //}

        //Dropdown, innitial index is set to "All" for the main page ONLY
        protected IEnumerable GetAssetTypes()
        {
            var types = AssetTypeManager.GetAsKeyValuePairs();
            var names = new SelectList(types, "Value", "Text");

            //setting innitial value to "All"
            var list = names.ToList();
            list.Insert(0, new SelectListItem
            {
                Text = "All",
                Value = "0"
            });
            return list;
        }
        public IActionResult GetAssetsByType(int id)
        {
            return ViewComponent("AssetsByType", id);
        }


    }//End of Controller
}//End of namespace

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Controllers/AssetTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.AssetTracking;
using Domain.AssetTracking;
using Microsoft.AspNetCore.Mvc;

namespace Presentation.AssetTracking.Controllers
{
    public class AssetTypeController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AssetType assetType)
        {
            try
            {
                AssetTypeManager.Add(assetType);
                return RedirectToAction("Create", "Asset");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Presentation.AssetTracking.Models;

namespace Presentation.AssetTracking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/Asset/Create.cshtml
@model Presentation.AssetTracking.Models.AssetViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Asset</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufacturer" class="control-label"></label>
                <input asp-for="Manufacturer" class="form-control" />
                <span asp-validation-for="Manufacturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssetTypeId" class="control-label"></label>
                <select asp-items="@ViewBag.AssetTypeId" asp-for="AssetTypeId" class="form-control"></select> @*Dropdown menu*@
                <span asp-validation-for="AssetTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TagNumber" class="control-label"></label>
                <input asp-for="TagNumber" class="form-control" />
                <span asp-validation-for="TagNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/Asset/Index.cshtml
@*@model IEnumerable<Presentation.AssetTracking.Models.AssetViewModel>*@

@{
    ViewData["Title"] = "Index";
}

<h3>Asset List</h3>
<hr />

<h6>Search by Asset Type</h6>

<select id="cboAssetTypes" asp-items="ViewBag.AssetTypes"></select>

<div id="uxDisplay">
    @await Component.InvokeAsync("AssetsByType", 0)
</div>


@section Scripts {
    <script>
        $(document).ready(function () { 
            //alert('loaded');
            $("#cboAssetTypes").change(function () {
                var assetTypeId = $("#cboAssetTypes").val();
                $.ajax({
                    method: 'GET',
                    url: 'Asset/GetAssetsByType', //I put "/" before Asset like he did, but it didnt work, took it off and worked beautifully, not sure why.
                    data: { id: assetTypeId }
                }).done(function (result, statusText, xhdr) {
                    $("#uxDisplay").html(result);
                });//Enf of AJAX
            });//end of cboAssetTypes
        });//End of document

    </script>
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/AssetType/Create.cshtml
@model Presentation.AssetTracking.Models.AssetTypeViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Asset Type</h1>
<br /><br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/Shared/Components/AssetsByType/Default.cshtml
@model IEnumerable<Presentation.AssetTracking.Models.AssetViewModel>

@{
    Layout = null;
}
<br /><br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TagNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssetType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TagNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssetType)
            </td>
        </tr>
}
    </tbody>
</table>

ASP.NET/ASP.NET Core MVC/YasinHabib_CPRG214_Lab2/Presentation.AssetTracking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asset Tracking System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Asset" asp-action="Index">Asset Tracking System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="Create">New Asset</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AssetType" asp-action="Create">New Asset-Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Asset Tracking System<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>